name: Generate EPG XMLTV File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build-epg:
    runs-on: ubuntu-latest

    # >>>>> ΑΛΛΑΓΗ 1: ΠΡΟΣΘΕΣΕ ΑΥΤΟ ΤΟ ΜΠΛΟΚ <<<<<
    # Δίνει στην Action δικαίωμα να γράψει στο αποθετήριο.
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run EPG generator script
        run: python generate_epg.py

      - name: Commit and push EPG file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated EPG update"
          # >>>>> ΑΛΛΑΓΗ 2: ΑΛΛΑΞΕ ΤΟ ΟΝΟΜΑ ΤΟΥ ΑΡΧΕΙΟΥ ΕΔΩ <<<<<
          file_pattern: dubai.epg.xml.gz
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
